Api/service
mesratn/secondEye pull request #23
Opened 2019-01-24 13:23 UTC by Shuuno

2019-01-24 22:02 UTC, mesratn requested changes
Hello
C'est bien, je vais test si ca fonctionne mais je vais pas merge tant que toutes les routes n'y sont pas comme ca sur le master y'a que les trucs complets et fonctionnels. Tu peux continuer a push sur cette branche en laissant la PR ouverte comme ca on fait des reviews au fur et a mesure

2019-01-24 22:02 UTC, mesratn commented on API/server.js
> +    app.use(morgan('combined'))
Serieux ? Ca s'appelle Morgan ? xD

2019-01-24 22:02 UTC, mesratn commented on API/api/controllers/faceController.js
> +                uri: process.env.FACE_API_URL + `persongroups/group1/persons/${savedIDs[0]}`,
Mais du coup cet appel devrait etre dans le service aussi non ?

2019-01-24 22:02 UTC, mesratn commented on API/api/services/microsoft.api.js
> +    return result;
Je pense que pour que ce soit vraiment un service portable et qu'on puisse changer d'API en claquant des doigts, il faut faire tout le traitement de la reponse ici. Que ca renvoit l'objet global et faces quoi. 
Comme ca si on a besoin de faire appel a l'API amazon par exemple, bah on change rien dans le controller, puisqu'apres le traitement la reponse sera la meme quelque soit l'API utilisee.

2019-01-30 11:01 UTC, Shuuno commented on API/api/services/microsoft.api.js
> +    return result;
Ah merde, j'aurais du lire ça avant de faire les modifications xD. 

J'ai commit un truc déjà, dis moi ce que tu en pense.

2019-03-08 09:40 UTC, mesratn approved these changes

2019-03-08 09:40 UTC, merged